### ISSUE TITLE
dosent save prefrence on new private tab

### ISSUE THREAD

**Issue by silverfang1321** [drunkg00se/Pixiv-Downloader#22]
### 描述错误 / Describe the bug

not sure if its a bug but to me it is

prefrence of settings not being saved in private tab

### 重现步骤 / To Reproduce

enable settings in normal tab e.g. ugoira to gif then in private tab its then reset to defaults

### 浏览器 / Browser

firefox

### 浏览器日志 / Browser logs

not rly loggable just settings getting restored to default

**Comment by drunkg00se** [comment]
This is the design of private mode. The `localStorage` of normal tabs and private tabs are isolated from each other.
